id: P004321
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC430
  title: 'བོད་ལྗོངས་ཀྱི་དགོན་སྡེའི་དཀར་ཆག་མུ་ཏིག་ཕྲེང་བ། —ལྷ་ས་གྲོང་མཐིལ་གྱི་དགོན་སྡེའི་སྐོར། '
  author: ''
  volumes:
    2fcfd129d5dc44a9bbda71e8c672dad6:
      image_group_id: I2PD18324
      title: ''
      volume_number: 1
      total_pages: 480
      base_file: v001.txt
