id: opecha:P004321
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC430
  title: 'བོད་ལྗོངས་ཀྱི་དགོན་སྡེའི་དཀར་ཆག་མུ་ཏིག་ཕྲེང་བ། —ལྷ་ས་གྲོང་མཐིལ་གྱི་དགོན་སྡེའི་སྐོར། '
  volume: ''
  author: ''
