id: IFFCC3F3C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:35:00+00:00'
last_modified: '2022-06-07T21:58:30.837442+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC430
  title: 'བོད་ལྗོངས་ཀྱི་དགོན་སྡེའི་དཀར་ཆག་མུ་ཏིག་ཕྲེང་བ། —ལྷ་ས་གྲོང་མཐིལ་གྱི་དགོན་སྡེའི་སྐོར། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    B36A:
      image_group_id: I2PD18324
      title: ''
      total_pages: 480
      order: 1
      base_file: B36A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
